export const universe=[
['000660.KS','SK하이닉스','KR','HBM · 메모리',['NVDA','MU']],['005930.KS','삼성전자','KR','메모리 · 반도체',['MU','AVGO']],['042700.KS','한미반도체','KR','HBM 장비',['NVDA','MU']],['267260.KS','HD현대일렉트릭','KR','데이터센터 전력',['MSFT','AMZN']],['010120.KS','LS ELECTRIC','KR','전력기기',['MSFT','GOOGL']],['034020.KS','두산에너빌리티','KR','원전',['CCJ']],['373220.KS','LG에너지솔루션','KR','EV · 배터리',['TSLA','GM']],['006400.KS','삼성SDI','KR','배터리',['TSLA','GM']],['005380.KS','현대차','KR','자동차',['GM','F']],['066570.KS','LG전자','KR','가전',['WHR']],
...['NVDA','MU','AVGO','MSFT','AMZN','GOOGL','CCJ','TSLA','GM','F','WHR'].map(s=>[s,s,'US','미국 선행 관찰',[]])
].map(([symbol,name,market,theme,links])=>({symbol,name,market,theme,links}));
export const indices=[['^GSPC','S&P 500'],['^NDX','NASDAQ 100'],['^SOX','PHLX SEMICONDUCTOR'],['^TNX','US 10Y']];
export function parseChart(raw,now=Date.now()){
 const c=raw?.chart?.result?.[0];if(!c?.meta)throw Error('가격 응답 없음');const m=c.meta;
 const bars=(c.timestamp||[]).map((t,i)=>({t,close:c.indicators?.quote?.[0]?.close?.[i],volume:c.indicators?.quote?.[0]?.volume?.[i]})).filter(b=>Number.isFinite(b.close)&&b.close>0);
 const price=m.regularMarketPrice,asOf=Number(m.regularMarketTime)*1000;if(!Number.isFinite(price)||price<=0||!Number.isFinite(asOf)||asOf>now+300000)throw Error('유효하지 않은 시세');
 const tz=m.exchangeTimezoneName||'UTC',day=t=>new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'}).format(t);
 const prior=bars.filter(b=>day(b.t*1000)<day(asOf));const previous=prior.at(-1)?.close;
 const history=prior.slice(-20);const ma20=history.length===20?history.reduce((a,b)=>a+b.close,0)/20:null;
 const averageVolume=history.length===20?history.reduce((a,b)=>a+(b.volume||0),0)/20:null;
 return {completed:Number.isFinite(m.currentTradingPeriod?.regular?.end)&&now>=m.currentTradingPeriod.regular.end*1000,price,currency:m.currency,asOf:new Date(asOf).toISOString(),ageHours:(now-asOf)/3600000,stale:now-asOf>96*3600000,previous:previous??null,change:previous?(price/previous-1)*100:null,ma20,volume:m.regularMarketVolume??null,volumeRatio:averageVolume&&m.regularMarketVolume?m.regularMarketVolume/averageVolume:null,source:'Yahoo Finance · 비공식 조회, 지연 가능',sourceUrl:`https://finance.yahoo.com/quote/${encodeURIComponent(m.symbol)}/`,session:'정규장 최근 체결 / 종가'};
}
export async function quote(symbol){const response=await fetch(`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?range=6mo&interval=1d`,{headers:{'User-Agent':'MarketRadar/1.0'},signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error(`시세 공급자 HTTP ${response.status}`);return parseChart(await response.json());}
export async function collect(){const results=[];const all=[...universe,...indices.map(([symbol,name])=>({symbol,name,market:'INDEX'}))];for(let i=0;i<all.length;i+=5){results.push(...await Promise.all(all.slice(i,i+5).map(async item=>{try{return {...item,quote:await quote(item.symbol)}}catch(e){return {...item,quote:null,error:e.message}}})));}return {generatedAt:new Date().toISOString(),items:results,provider:'Yahoo Finance',mode:'observations'};}
export function assess(item){const q=item.quote;if(!q||q.stale)return {label:'UNAVAILABLE',reason:q?'시세가 96시간 이상 오래되었습니다.':'시세 조회 실패',score:null};if(q.change===null)return {label:'UNAVAILABLE',reason:'전일 종가가 없어 등락률 계산 불가',score:null};if(q.change<=-5)return {label:'AVOID',reason:'최근 정규장 가격이 전일 종가 대비 5% 이상 하락 · 신규 진입 주의',score:null};if(q.change>=7)return {label:'AVOID',reason:'전일 종가 대비 7% 이상 상승 · 추격 진입 주의',score:null};return {label:'WATCH',reason:q.ma20&&q.price<q.ma20?'직전 20거래일 평균 아래 · 추세 회복 확인':'가격 관찰 중 · 공시와 이벤트 원문 확인 필요',score:null};}
